### ISSUE TITLE
SIBELIUS-DARK code for matter density plots

### ISSUE THREAD

**Issue by osokoliuk** [stuartmcalpine/sibelius_scripts#1]
Hi! I was wondering, will it be possible to privately share the code, that you've used to plot matter density distributions for your SIBELIUS-DARK paper (i.e Figure 18 in 2202.04099)? We will then be more than happy to add you to the list of co-authors in our upcoming paper, where such plots will be used. If you are interested, please send an email to oleksii.sokoliuk@mao.kiev.ua (sorry for such form of communication, but is seems that your Helsinki University email does not work).

With the best wishes, Oleksii Sokoliuk
MAO NAS of Ukraine

**Comment by stuartmcalpine** [comment]
Hey!

The code I used to make that particular image is not available I'm afraid, but something like http://alejandrobll.github.io/py-sphviewer/index.html should do the trick!

**Comment by osokoliuk** [comment]
I see. Thank you, will check that code later!
